(function(){'use strict';
var canvas=document.getElementById('slopeCanvas'),ctx=canvas.getContext('2d'),W=960,H=540;
var STATES={MENU:'MENU',PLAYING:'PLAYING',PAUSED:'PAUSED',GAME_OVER:'GAME_OVER',SETTINGS:'SETTINGS'},state=STATES.MENU;
var settings={music:.35,sound:.6,quality:'high',shake:true,reduced:false};try{settings=Object.assign(settings,JSON.parse(localStorage.getItem('orr-slope-settings')||'{}'))}catch(e){}
var store={best:0,games:0};try{store=Object.assign(store,JSON.parse(localStorage.getItem('orr-slope-save')||'{}'))}catch(e){}
var seed=583921,rng=function(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
var input={left:false,right:false},player,track=[],objects=[],particles=[],camera={x:0,y:0,z:0,roll:0},score=0,distance=0,combo=1,speed=9,last=0,spawnZ=0,runSeed=0;
function save(){try{localStorage.setItem('orr-slope-save',JSON.stringify(store));localStorage.setItem('orr-slope-settings',JSON.stringify(settings))}catch(e){}}
function el(id){return document.getElementById(id)}
function start(){runSeed=(Date.now()>>>0)^583921;seed=runSeed;track=[];objects=[];particles=[];player={x:0,y:0,z:0,vx:0,vy:0,r:18,air:0};camera={x:0,y:0,z:0,roll:0};score=0;distance=0;combo=1;speed=9;spawnZ=0;state=STATES.PLAYING;store.games++;generate(240);updateUi()}
function generate(until){while(spawnZ<until){var difficulty=Math.min(1,spawnZ/10000),width=290-difficulty*80+(rng()*35),turn=(rng()-.5)*70,kind=rng();var section={z:spawnZ,len:260,width:width,center:turn,depth:kind>.8?38:0,slope:(rng()-.5)*.08};track.push(section);if(spawnZ>300){var count=kind>.72?2:1;for(var i=0;i<count;i++){var type=rng(),oz=spawnZ+80+rng()*130;objects.push({z:oz,x:turn+(rng()-.5)*width*.65,type:type<.24?'block':type<.42?'slide':type<.58?'rotor':type<.72?'gap':type<.86?'wall':'ramp',w:type<.42?38:55,h:36,phase:rng()*6})}}spawnZ+=section.len}}
function currentSection(){for(var i=track.length-1;i>=0;i--)if(player.z>=track[i].z)return track[i];return track[0]}
function project(x,y,z){var dz=z-camera.z;if(dz<8)return null;var f=650/dz;return{x:W/2+(x-camera.x)*f,y:H*.43+(y-camera.y)*f,scale:f}}
function crash(){state=STATES.GAME_OVER;combo=1;store.best=Math.max(store.best,Math.floor(score));save();for(var i=0;i<30;i++)particles.push({x:player.x,y:player.y,z:player.z,vx:(rng()-.5)*300,vy:(rng()-.5)*300,vz:rng()*100,life:1})}
function update(dt){if(state!==STATES.PLAYING)return;var sec=currentSection();generate(player.z+700);var steer=(input.left?-1:0)+(input.right?1:0);player.vx+=steer*760*dt;player.vx*=Math.pow(.001,dt);player.x+=player.vx*dt;player.z+=(speed*60)*dt;distance=player.z/10;speed=Math.min(25,speed+dt*.22);player.y=0;player.air=Math.max(0,player.air-dt);camera.x+=(player.x-camera.x)*Math.min(1,dt*7);camera.z+=(player.z-camera.z)*Math.min(1,dt*9);camera.roll+=(player.vx/250-camera.roll)*Math.min(1,dt*5);var safe=sec.width/2;if(Math.abs(player.x-sec.center)>safe){crash();return}objects.forEach(function(o){if(o.hit||Math.abs(o.z-player.z)>45)return;if(o.type==='gap'&&Math.abs(player.x-o.x)<o.w&&player.air<=0){crash();return}if(o.type!=='gap'&&Math.abs(player.x-o.x)<o.w&&player.air<=0){crash();return}if(o.type==='ramp'&&Math.abs(player.x-o.x)<o.w){player.air=.55;player.vy=300}});score+=dt*speed*combo;combo=Math.min(9,1+Math.floor(distance/300));if(player.z%90<speed)particles.push({x:player.x,y:0,z:player.z,life:1,vx:0,vy:0,vz:0});particles.forEach(function(p){p.z+=p.vz*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(function(p){return p.life>0});updateUi()}
function draw(){ctx.fillStyle='#050817';ctx.fillRect(0,0,W,H);var grd=ctx.createLinearGradient(0,0,0,H);grd.addColorStop(0,'#111d48');grd.addColorStop(.55,'#090e29');grd.addColorStop(1,'#02030b');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2,H*.43);ctx.rotate(-camera.roll*.1);for(var z=Math.floor(camera.z/80)*80;z<camera.z+1000;z+=80){var s=project(0,0,z);if(!s)continue;ctx.strokeStyle='rgba(66,245,208,'+Math.max(.08,1-s.scale/12)+')';ctx.beginPath();ctx.moveTo(-W, s.y);ctx.lineTo(W,s.y);ctx.stroke()}ctx.restore();track.forEach(function(t){if(t.z+t.len<camera.z+20||t.z>camera.z+1100)return;var near=project(t.center-t.width/2,0,t.z),far=project(t.center+t.width/2,0,t.z+t.len);if(!near||!far)return;ctx.fillStyle='#101a36';ctx.beginPath();ctx.moveTo(near.x,near.y);ctx.lineTo(near.x+near.scale*t.width,near.y);ctx.lineTo(far.x+far.scale*t.width,far.y);ctx.lineTo(far.x,far.y);ctx.fill();ctx.strokeStyle='#42f5d066';ctx.stroke();var edge=project(t.center-t.width/2-8,0,t.z);ctx.strokeStyle='#42f5d0';ctx.beginPath();ctx.moveTo(edge.x,edge.y);ctx.lineTo(edge.x,far.y);ctx.stroke()});objects.forEach(function(o){if(o.z<camera.z+20||o.z>camera.z+1100)return;var p=project(o.x,0,o.z);if(!p)return;ctx.save();ctx.translate(p.x,p.y);var col=o.type==='gap'?'#090914':o.type==='ramp'?'#42f5d0':'#ff4f6d';ctx.fillStyle=col;ctx.shadowBlur=18;ctx.shadowColor=col;if(o.type==='rotor'){ctx.rotate(o.phase+performance.now()/500);ctx.fillRect(-p.scale*o.w/2,-p.scale*o.h,p.scale*o.w,p.scale*8)}else if(o.type==='gap'){ctx.strokeStyle='#ff4f6d';ctx.lineWidth=3;ctx.strokeRect(-p.scale*o.w/2,-3,p.scale*o.w,7)}else{ctx.fillRect(-p.scale*o.w/2,-p.scale*o.h,p.scale*o.w,p.scale*o.h)}ctx.restore()});var pp=project(player.x,0,player.z);if(pp){ctx.save();ctx.translate(pp.x,pp.y-pp.scale*player.r);ctx.fillStyle='#65f5ff';ctx.shadowBlur=28;ctx.shadowColor='#65f5ff';ctx.beginPath();ctx.arc(0,0,Math.max(5,pp.scale*player.r),0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-pp.scale*5,-pp.scale*6,Math.max(2,pp.scale*4),0,Math.PI*2);ctx.fill();ctx.restore()}particles.forEach(function(p){var q=project(p.x,p.y,p.z);if(q){ctx.globalAlpha=p.life;ctx.fillStyle='#65f5ff';ctx.fillRect(q.x,q.y,3,3)}});ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.font='bold 18px Space Mono';ctx.fillText('NEON DESCENT',24,32);if(state===STATES.MENU||state===STATES.GAME_OVER||state===STATES.PAUSED||state===STATES.SETTINGS){ctx.fillStyle='#050817dd';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#65f5ff';ctx.font='bold 44px Archivo Black';ctx.fillText(state===STATES.MENU?'NEON DESCENT':state===STATES.GAME_OVER?'RUN ENDED':state==='PAUSED'?'PAUSED':'SETTINGS',W/2,170);ctx.fillStyle='#fff';ctx.font='18px Space Mono';if(state===STATES.MENU)ctx.fillText('A/D or ←/→ to steer · Touch controls supported',W/2,215);if(state===STATES.GAME_OVER)ctx.fillText('Score '+Math.floor(score)+' · Best '+store.best,W/2,215);ctx.textAlign='left'}}
function updateUi(){el('runnerScore').textContent=Math.floor(score);el('runnerBest').textContent=store.best;el('runnerSpeed').textContent=(speed*10).toFixed(0);el('runnerDistance').textContent=Math.floor(distance);el('runnerCombo').textContent='x'+combo}
function frame(now){var dt=Math.min(.034,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(frame)}
function bind(id,prop){var b=el(id);b.addEventListener('pointerdown',function(e){e.preventDefault();input[prop]=true});['pointerup','pointercancel','pointerleave'].forEach(function(t){b.addEventListener(t,function(){input[prop]=false})})}
bind('steerLeft','left');bind('steerRight','right');el('runnerPlay').onclick=function(){start()};el('runnerRestart').onclick=function(){start()};el('runnerPause').onclick=function(){if(state===STATES.PLAYING)state=STATES.PAUSED;else if(state===STATES.PAUSED)state=STATES.PLAYING};el('runnerSettings').onclick=function(){state=state===STATES.SETTINGS?STATES.MENU:STATES.SETTINGS};el('runnerReduce').onclick=function(){settings.reduced=!settings.reduced;save()};document.addEventListener('keydown',function(e){if(e.code==='ArrowLeft'||e.code==='KeyA')input.left=true;if(e.code==='ArrowRight'||e.code==='KeyD')input.right=true;if(e.code==='Space'&&state===STATES.MENU)start();if(e.code==='KeyP'&&state!==STATES.GAME_OVER)el('runnerPause').click()});document.addEventListener('keyup',function(e){if(e.code==='ArrowLeft'||e.code==='KeyA')input.left=false;if(e.code==='ArrowRight'||e.code==='KeyD')input.right=false});canvas.addEventListener('pointerdown',function(e){if(state===STATES.GAME_OVER)start();var r=canvas.getBoundingClientRect();if(e.clientX<r.left+r.width/2)input.left=true;else input.right=true});canvas.addEventListener('pointerup',function(){input.left=input.right=false});el('runnerHigh').textContent=store.best;requestAnimationFrame(frame);
})();